//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod subscription_bulk;
pub mod subscription_billing_run_bulk;
pub mod subscription_plan_bulk;
pub mod subscription_plan_line_bulk;

pub use subscription_bulk::SubscriptionBulkService;
pub use subscription_billing_run_bulk::SubscriptionBillingRunBulkService;
pub use subscription_plan_bulk::SubscriptionPlanBulkService;
pub use subscription_plan_line_bulk::SubscriptionPlanLineBulkService;

// <<< CUSTOM
// END CUSTOM
