//! Bulk operations for SubscriptionBillingRun entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSubscriptionBillingRunDto;
use crate::application::service::SubscriptionBillingRunService;
use crate::domain::entity::SubscriptionBillingRun;

/// Bulk operation handler for SubscriptionBillingRun entities.
///
/// Wraps `SubscriptionBillingRunService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SubscriptionBillingRunBulkService = GenericBulkService<SubscriptionBillingRun, CreateSubscriptionBillingRunDto, SubscriptionBillingRunService>;

// <<< CUSTOM
// END CUSTOM
