//! Bulk operations for Subscription entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSubscriptionDto;
use crate::application::service::SubscriptionService;
use crate::domain::entity::Subscription;

/// Bulk operation handler for Subscription entities.
///
/// Wraps `SubscriptionService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SubscriptionBulkService = GenericBulkService<Subscription, CreateSubscriptionDto, SubscriptionService>;

// <<< CUSTOM
// END CUSTOM
