//! Bulk operations for SubscriptionPlanLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSubscriptionPlanLineDto;
use crate::application::service::SubscriptionPlanLineService;
use crate::domain::entity::SubscriptionPlanLine;

/// Bulk operation handler for SubscriptionPlanLine entities.
///
/// Wraps `SubscriptionPlanLineService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SubscriptionPlanLineBulkService = GenericBulkService<SubscriptionPlanLine, CreateSubscriptionPlanLineDto, SubscriptionPlanLineService>;

// <<< CUSTOM
// END CUSTOM
