//! Bulk operations for SubscriptionPlan entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSubscriptionPlanDto;
use crate::application::service::SubscriptionPlanService;
use crate::domain::entity::SubscriptionPlan;

/// Bulk operation handler for SubscriptionPlan entities.
///
/// Wraps `SubscriptionPlanService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SubscriptionPlanBulkService = GenericBulkService<SubscriptionPlan, CreateSubscriptionPlanDto, SubscriptionPlanService>;

// <<< CUSTOM
// END CUSTOM
