//! SubscriptionBillingRun DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SubscriptionBillingRun;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BillingRunStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SubscriptionBillingRun
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSubscriptionBillingRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "subscription_id")]
    pub subscription_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_start")]
    pub period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_end")]
    pub period_end: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "due_date")]
    pub due_date: NaiveDate,
    #[serde(alias = "grand_total")]
    pub grand_total: Decimal,
    pub status: BillingRunStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "invoice_id")]
    pub invoice_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "idempotency_key")]
    pub idempotency_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "attempted_at")]
    pub attempted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SubscriptionBillingRun
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSubscriptionBillingRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "subscription_id")]
    pub subscription_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_start")]
    pub period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "period_end")]
    pub period_end: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "due_date")]
    pub due_date: NaiveDate,
    #[serde(alias = "grand_total")]
    pub grand_total: Decimal,
    pub status: BillingRunStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "invoice_id")]
    pub invoice_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "idempotency_key")]
    pub idempotency_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "attempted_at")]
    pub attempted_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SubscriptionBillingRun
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSubscriptionBillingRunDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "subscription_id")]
    pub subscription_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "period_start")]
    pub period_start: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "period_end")]
    pub period_end: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "grand_total")]
    pub grand_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<BillingRunStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_id")]
    pub invoice_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "idempotency_key")]
    pub idempotency_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "attempted_at")]
    pub attempted_at: Option<DateTime<Utc>>,
}

impl PatchSubscriptionBillingRunDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.subscription_id.is_some() || self.company_id.is_some() || self.period_start.is_some() || self.period_end.is_some() || self.due_date.is_some() || self.grand_total.is_some() || self.status.is_some() || self.invoice_id.is_some() || self.idempotency_key.is_some() || self.attempted_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SubscriptionBillingRun entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionBillingRunResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub subscription_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub period_end: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub due_date: NaiveDate,
    pub grand_total: Decimal,
    pub status: BillingRunStatus,
    pub invoice_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub idempotency_key: String,
    pub attempted_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SubscriptionBillingRun entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionBillingRunListResponseDto {
    /// List of items
    pub items: Vec<SubscriptionBillingRunResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SubscriptionBillingRunListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SubscriptionBillingRunResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionBillingRunSummaryDto {
    pub id: Uuid,
    pub subscription_id: Uuid,
    pub company_id: Uuid,
    pub period_start: NaiveDate,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SubscriptionBillingRun> for SubscriptionBillingRunResponseDto {
    fn from(entity: SubscriptionBillingRun) -> Self {
        Self {
            id: entity.id,
            subscription_id: entity.subscription_id,
            company_id: entity.company_id,
            period_start: entity.period_start,
            period_end: entity.period_end,
            due_date: entity.due_date,
            grand_total: entity.grand_total,
            status: entity.status,
            invoice_id: entity.invoice_id,
            idempotency_key: entity.idempotency_key,
            attempted_at: entity.attempted_at,
            metadata: entity.metadata,
        }
    }
}

impl From<SubscriptionBillingRun> for SubscriptionBillingRunSummaryDto {
    fn from(entity: SubscriptionBillingRun) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            subscription_id: entity.subscription_id,
            company_id: entity.company_id,
            period_start: entity.period_start,
            created_at,
        }
    }
}

impl From<CreateSubscriptionBillingRunDto> for SubscriptionBillingRun {
    fn from(dto: CreateSubscriptionBillingRunDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            subscription_id: dto.subscription_id,
            company_id: dto.company_id,
            period_start: dto.period_start,
            period_end: dto.period_end,
            due_date: dto.due_date,
            grand_total: dto.grand_total,
            status: dto.status,
            invoice_id: dto.invoice_id,
            idempotency_key: dto.idempotency_key,
            attempted_at: dto.attempted_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SubscriptionBillingRun> for SubscriptionBillingRunResponseDto {
    fn from(entity: &SubscriptionBillingRun) -> Self {
        Self {
            id: entity.id.clone(),
            subscription_id: entity.subscription_id.clone(),
            company_id: entity.company_id.clone(),
            period_start: entity.period_start.clone(),
            period_end: entity.period_end.clone(),
            due_date: entity.due_date.clone(),
            grand_total: entity.grand_total.clone(),
            status: entity.status.clone(),
            invoice_id: entity.invoice_id.clone(),
            idempotency_key: entity.idempotency_key.clone(),
            attempted_at: entity.attempted_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSubscriptionBillingRunDto> for SubscriptionBillingRun {
    fn from_create_dto(dto: CreateSubscriptionBillingRunDto) -> backbone_core::ServiceResult<Self> {
        Ok(SubscriptionBillingRun::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSubscriptionBillingRunDto> for SubscriptionBillingRun {
    fn apply_update(mut self, dto: UpdateSubscriptionBillingRunDto) -> backbone_core::ServiceResult<Self> {
        self.subscription_id = dto.subscription_id;
        self.company_id = dto.company_id;
        self.period_start = dto.period_start;
        self.period_end = dto.period_end;
        self.due_date = dto.due_date;
        self.grand_total = dto.grand_total;
        self.status = dto.status;
        self.invoice_id = dto.invoice_id;
        self.idempotency_key = dto.idempotency_key;
        self.attempted_at = dto.attempted_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SubscriptionBillingRun here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

