//! SubscriptionPlanLine DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SubscriptionPlanLine;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SubscriptionPlanLine
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSubscriptionPlanLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "plan_id")]
    pub plan_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    #[serde(alias = "unit_price")]
    pub unit_price: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SubscriptionPlanLine
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSubscriptionPlanLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "plan_id")]
    pub plan_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "account_id")]
    pub account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    #[serde(alias = "unit_price")]
    pub unit_price: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SubscriptionPlanLine
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSubscriptionPlanLineDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "plan_id")]
    pub plan_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "account_id")]
    pub account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unit_price")]
    pub unit_price: Option<Decimal>,
}

impl PatchSubscriptionPlanLineDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.plan_id.is_some() || self.item_id.is_some() || self.account_id.is_some() || self.description.is_some() || self.quantity.is_some() || self.unit_price.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SubscriptionPlanLine entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionPlanLineResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub plan_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub account_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SubscriptionPlanLine entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionPlanLineListResponseDto {
    /// List of items
    pub items: Vec<SubscriptionPlanLineResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SubscriptionPlanLineListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SubscriptionPlanLineResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionPlanLineSummaryDto {
    pub id: Uuid,
    pub plan_id: Uuid,
    pub item_id: Uuid,
    pub account_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SubscriptionPlanLine> for SubscriptionPlanLineResponseDto {
    fn from(entity: SubscriptionPlanLine) -> Self {
        Self {
            id: entity.id,
            plan_id: entity.plan_id,
            item_id: entity.item_id,
            account_id: entity.account_id,
            description: entity.description,
            quantity: entity.quantity,
            unit_price: entity.unit_price,
            metadata: entity.metadata,
        }
    }
}

impl From<SubscriptionPlanLine> for SubscriptionPlanLineSummaryDto {
    fn from(entity: SubscriptionPlanLine) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            plan_id: entity.plan_id,
            item_id: entity.item_id,
            account_id: entity.account_id,
            created_at,
        }
    }
}

impl From<CreateSubscriptionPlanLineDto> for SubscriptionPlanLine {
    fn from(dto: CreateSubscriptionPlanLineDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            plan_id: dto.plan_id,
            item_id: dto.item_id,
            account_id: dto.account_id,
            description: dto.description,
            quantity: dto.quantity,
            unit_price: dto.unit_price,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SubscriptionPlanLine> for SubscriptionPlanLineResponseDto {
    fn from(entity: &SubscriptionPlanLine) -> Self {
        Self {
            id: entity.id.clone(),
            plan_id: entity.plan_id.clone(),
            item_id: entity.item_id.clone(),
            account_id: entity.account_id.clone(),
            description: entity.description.clone(),
            quantity: entity.quantity.clone(),
            unit_price: entity.unit_price.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSubscriptionPlanLineDto> for SubscriptionPlanLine {
    fn from_create_dto(dto: CreateSubscriptionPlanLineDto) -> backbone_core::ServiceResult<Self> {
        Ok(SubscriptionPlanLine::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSubscriptionPlanLineDto> for SubscriptionPlanLine {
    fn apply_update(mut self, dto: UpdateSubscriptionPlanLineDto) -> backbone_core::ServiceResult<Self> {
        self.plan_id = dto.plan_id;
        self.item_id = dto.item_id;
        self.account_id = dto.account_id;
        self.description = dto.description;
        self.quantity = dto.quantity;
        self.unit_price = dto.unit_price;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SubscriptionPlanLine here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
