//! SubscriptionPlan DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SubscriptionPlan;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::BillingCycle;
use crate::domain::entity::SubscriptionPlanStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SubscriptionPlan
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSubscriptionPlanDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "plan_code")]
    pub plan_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "billing_cycle")]
    pub billing_cycle: BillingCycle,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "billing_day")]
    pub billing_day: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "receivable_account_id")]
    pub receivable_account_id: Uuid,
    pub price: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "trial_days")]
    pub trial_days: Option<i32>,
    pub status: SubscriptionPlanStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SubscriptionPlan
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSubscriptionPlanDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "plan_code")]
    pub plan_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(alias = "billing_cycle")]
    pub billing_cycle: BillingCycle,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "billing_day")]
    pub billing_day: i32,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "receivable_account_id")]
    pub receivable_account_id: Uuid,
    pub price: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "trial_days")]
    pub trial_days: Option<i32>,
    pub status: SubscriptionPlanStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SubscriptionPlan
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSubscriptionPlanDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "plan_code")]
    pub plan_code: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "billing_cycle")]
    pub billing_cycle: Option<BillingCycle>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "billing_day")]
    pub billing_day: Option<i32>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "receivable_account_id")]
    pub receivable_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub price: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "trial_days")]
    pub trial_days: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SubscriptionPlanStatus>,
}

impl PatchSubscriptionPlanDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.plan_code.is_some() || self.name.is_some() || self.description.is_some() || self.company_id.is_some() || self.billing_cycle.is_some() || self.billing_day.is_some() || self.currency.is_some() || self.receivable_account_id.is_some() || self.price.is_some() || self.trial_days.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SubscriptionPlan entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionPlanResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub plan_code: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub billing_cycle: BillingCycle,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub billing_day: i32,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub receivable_account_id: Uuid,
    pub price: Decimal,
    pub trial_days: Option<i32>,
    pub status: SubscriptionPlanStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SubscriptionPlan entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionPlanListResponseDto {
    /// List of items
    pub items: Vec<SubscriptionPlanResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SubscriptionPlanListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SubscriptionPlanResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionPlanSummaryDto {
    pub id: Uuid,
    pub plan_code: String,
    pub name: String,
    pub description: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SubscriptionPlan> for SubscriptionPlanResponseDto {
    fn from(entity: SubscriptionPlan) -> Self {
        Self {
            id: entity.id,
            plan_code: entity.plan_code,
            name: entity.name,
            description: entity.description,
            company_id: entity.company_id,
            billing_cycle: entity.billing_cycle,
            billing_day: entity.billing_day,
            currency: entity.currency,
            receivable_account_id: entity.receivable_account_id,
            price: entity.price,
            trial_days: entity.trial_days,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<SubscriptionPlan> for SubscriptionPlanSummaryDto {
    fn from(entity: SubscriptionPlan) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            plan_code: entity.plan_code,
            name: entity.name,
            description: entity.description,
            created_at,
        }
    }
}

impl From<CreateSubscriptionPlanDto> for SubscriptionPlan {
    fn from(dto: CreateSubscriptionPlanDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            plan_code: dto.plan_code,
            name: dto.name,
            description: dto.description,
            company_id: dto.company_id,
            billing_cycle: dto.billing_cycle,
            billing_day: dto.billing_day,
            currency: dto.currency,
            receivable_account_id: dto.receivable_account_id,
            price: dto.price,
            trial_days: dto.trial_days,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SubscriptionPlan> for SubscriptionPlanResponseDto {
    fn from(entity: &SubscriptionPlan) -> Self {
        Self {
            id: entity.id.clone(),
            plan_code: entity.plan_code.clone(),
            name: entity.name.clone(),
            description: entity.description.clone(),
            company_id: entity.company_id.clone(),
            billing_cycle: entity.billing_cycle.clone(),
            billing_day: entity.billing_day.clone(),
            currency: entity.currency.clone(),
            receivable_account_id: entity.receivable_account_id.clone(),
            price: entity.price.clone(),
            trial_days: entity.trial_days.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSubscriptionPlanDto> for SubscriptionPlan {
    fn from_create_dto(dto: CreateSubscriptionPlanDto) -> backbone_core::ServiceResult<Self> {
        Ok(SubscriptionPlan::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSubscriptionPlanDto> for SubscriptionPlan {
    fn apply_update(mut self, dto: UpdateSubscriptionPlanDto) -> backbone_core::ServiceResult<Self> {
        self.plan_code = dto.plan_code;
        self.name = dto.name;
        self.description = dto.description;
        self.company_id = dto.company_id;
        self.billing_cycle = dto.billing_cycle;
        self.billing_day = dto.billing_day;
        self.currency = dto.currency;
        self.receivable_account_id = dto.receivable_account_id;
        self.price = dto.price;
        self.trial_days = dto.trial_days;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SubscriptionPlan here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

