//! Subscription DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Subscription;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SubscriptionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Subscription
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSubscriptionDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "subscription_number")]
    pub subscription_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "plan_id")]
    pub plan_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    pub status: SubscriptionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "started_at")]
    pub started_at: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "current_period_start")]
    pub current_period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "current_period_end")]
    pub current_period_end: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "next_billing_date")]
    pub next_billing_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cancelled_at")]
    pub cancelled_at: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ended_at")]
    pub ended_at: Option<NaiveDate>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Subscription
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSubscriptionDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "subscription_number")]
    pub subscription_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "plan_id")]
    pub plan_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    pub status: SubscriptionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "started_at")]
    pub started_at: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "current_period_start")]
    pub current_period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "current_period_end")]
    pub current_period_end: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "next_billing_date")]
    pub next_billing_date: NaiveDate,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cancelled_at")]
    pub cancelled_at: Option<NaiveDate>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "ended_at")]
    pub ended_at: Option<NaiveDate>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Subscription
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSubscriptionDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "subscription_number")]
    pub subscription_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "plan_id")]
    pub plan_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SubscriptionStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "started_at")]
    pub started_at: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "current_period_start")]
    pub current_period_start: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "current_period_end")]
    pub current_period_end: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "next_billing_date")]
    pub next_billing_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cancelled_at")]
    pub cancelled_at: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "ended_at")]
    pub ended_at: Option<NaiveDate>,
}

impl PatchSubscriptionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.subscription_number.is_some() || self.company_id.is_some() || self.customer_id.is_some() || self.plan_id.is_some() || self.branch_id.is_some() || self.status.is_some() || self.started_at.is_some() || self.current_period_start.is_some() || self.current_period_end.is_some() || self.next_billing_date.is_some() || self.currency.is_some() || self.cancelled_at.is_some() || self.ended_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Subscription entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub subscription_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub plan_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub status: SubscriptionStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub started_at: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub current_period_start: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub current_period_end: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub next_billing_date: NaiveDate,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub cancelled_at: Option<NaiveDate>,
    pub ended_at: Option<NaiveDate>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Subscription entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionListResponseDto {
    /// List of items
    pub items: Vec<SubscriptionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SubscriptionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SubscriptionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SubscriptionSummaryDto {
    pub id: Uuid,
    pub subscription_number: String,
    pub company_id: Uuid,
    pub customer_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Subscription> for SubscriptionResponseDto {
    fn from(entity: Subscription) -> Self {
        Self {
            id: entity.id,
            subscription_number: entity.subscription_number,
            company_id: entity.company_id,
            customer_id: entity.customer_id,
            plan_id: entity.plan_id,
            branch_id: entity.branch_id,
            status: entity.status,
            started_at: entity.started_at,
            current_period_start: entity.current_period_start,
            current_period_end: entity.current_period_end,
            next_billing_date: entity.next_billing_date,
            currency: entity.currency,
            cancelled_at: entity.cancelled_at,
            ended_at: entity.ended_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Subscription> for SubscriptionSummaryDto {
    fn from(entity: Subscription) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            subscription_number: entity.subscription_number,
            company_id: entity.company_id,
            customer_id: entity.customer_id,
            created_at,
        }
    }
}

impl From<CreateSubscriptionDto> for Subscription {
    fn from(dto: CreateSubscriptionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            subscription_number: dto.subscription_number,
            company_id: dto.company_id,
            customer_id: dto.customer_id,
            plan_id: dto.plan_id,
            branch_id: dto.branch_id,
            status: dto.status,
            started_at: dto.started_at,
            current_period_start: dto.current_period_start,
            current_period_end: dto.current_period_end,
            next_billing_date: dto.next_billing_date,
            currency: dto.currency,
            cancelled_at: dto.cancelled_at,
            ended_at: dto.ended_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Subscription> for SubscriptionResponseDto {
    fn from(entity: &Subscription) -> Self {
        Self {
            id: entity.id.clone(),
            subscription_number: entity.subscription_number.clone(),
            company_id: entity.company_id.clone(),
            customer_id: entity.customer_id.clone(),
            plan_id: entity.plan_id.clone(),
            branch_id: entity.branch_id.clone(),
            status: entity.status.clone(),
            started_at: entity.started_at.clone(),
            current_period_start: entity.current_period_start.clone(),
            current_period_end: entity.current_period_end.clone(),
            next_billing_date: entity.next_billing_date.clone(),
            currency: entity.currency.clone(),
            cancelled_at: entity.cancelled_at.clone(),
            ended_at: entity.ended_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSubscriptionDto> for Subscription {
    fn from_create_dto(dto: CreateSubscriptionDto) -> backbone_core::ServiceResult<Self> {
        Ok(Subscription::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSubscriptionDto> for Subscription {
    fn apply_update(mut self, dto: UpdateSubscriptionDto) -> backbone_core::ServiceResult<Self> {
        self.subscription_number = dto.subscription_number;
        self.company_id = dto.company_id;
        self.customer_id = dto.customer_id;
        self.plan_id = dto.plan_id;
        self.branch_id = dto.branch_id;
        self.status = dto.status;
        self.started_at = dto.started_at;
        self.current_period_start = dto.current_period_start;
        self.current_period_end = dto.current_period_end;
        self.next_billing_date = dto.next_billing_date;
        self.currency = dto.currency;
        self.cancelled_at = dto.cancelled_at;
        self.ended_at = dto.ended_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Subscription here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

