//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod subscription_specification;
pub mod subscription_billing_run_specification;
pub mod subscription_plan_specification;
pub mod subscription_plan_line_specification;

// <<< CUSTOM
// END CUSTOM
