//! Domain policy for SubscriptionBillingRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::SubscriptionBillingRun;

/// Domain policy for SubscriptionBillingRun — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<SubscriptionBillingRun>` in the `// <<< CUSTOM` zone.
pub type SubscriptionBillingRunDomainPolicy = PermitAllPolicy<SubscriptionBillingRun>;

// <<< CUSTOM
// END CUSTOM
