//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod subscription_service;
pub mod subscription_billing_run_service;
pub mod subscription_plan_service;
pub mod subscription_plan_line_service;

// <<< CUSTOM
pub mod subscription_events;
pub mod subscription_write_service;
pub use subscription_events::{
    DueLine, LoggingSink, SubscriptionEvent, SubscriptionEventSink, SubscriptionInvoiceDue,
};
pub use subscription_write_service::{SubscriptionError, SubscriptionWriteService};
// END CUSTOM

pub use subscription_service::SubscriptionService;
pub use subscription_billing_run_service::SubscriptionBillingRunService;
pub use subscription_plan_service::SubscriptionPlanService;
pub use subscription_plan_line_service::SubscriptionPlanLineService;
// <<< CUSTOM
// END CUSTOM
