//! Application service for SubscriptionBillingRun entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `subscription_billing_run_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSubscriptionBillingRunDto, UpdateSubscriptionBillingRunDto};
use crate::domain::entity::SubscriptionBillingRun;
use crate::infrastructure::persistence::SubscriptionBillingRunRepository;

/// Application service for SubscriptionBillingRun entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `subscription_billing_run_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SubscriptionBillingRunServiceCustom {
///     inner: Arc<SubscriptionBillingRunService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SubscriptionBillingRunService = GenericCrudService<
    SubscriptionBillingRun,
    CreateSubscriptionBillingRunDto,
    UpdateSubscriptionBillingRunDto,
    SubscriptionBillingRunRepository,
>;

// <<< CUSTOM
// END CUSTOM
