//! Application service for Subscription entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `subscription_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSubscriptionDto, UpdateSubscriptionDto};
use crate::domain::entity::Subscription;
use crate::infrastructure::persistence::SubscriptionRepository;

/// Application service for Subscription entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `subscription_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SubscriptionServiceCustom {
///     inner: Arc<SubscriptionService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SubscriptionService = GenericCrudService<
    Subscription,
    CreateSubscriptionDto,
    UpdateSubscriptionDto,
    SubscriptionRepository,
>;

// <<< CUSTOM
// END CUSTOM
