//! Application service for SubscriptionPlan entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `subscription_plan_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSubscriptionPlanDto, UpdateSubscriptionPlanDto};
use crate::domain::entity::SubscriptionPlan;
use crate::infrastructure::persistence::SubscriptionPlanRepository;

/// Application service for SubscriptionPlan entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `subscription_plan_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SubscriptionPlanServiceCustom {
///     inner: Arc<SubscriptionPlanService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SubscriptionPlanService = GenericCrudService<
    SubscriptionPlan,
    CreateSubscriptionPlanDto,
    UpdateSubscriptionPlanDto,
    SubscriptionPlanRepository,
>;

// <<< CUSTOM
// END CUSTOM
