-- SubscriptionBillingRun Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the subscription.subscription_billing_runs table.
-- Customize this file to add your initial data.

-- INSERT INTO subscription.subscription_billing_runs (
--     id,
--     subscription_id,
--     period_start,
--     period_end,
--     due_date,
--     grand_total,
--     status,
--     invoice_id,
--     idempotency_key,
--     attempted_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO subscription.subscription_billing_runs (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

