-- Subscription Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the subscription.subscriptions table.
-- Customize this file to add your initial data.

-- INSERT INTO subscription.subscriptions (
--     id,
--     subscription_number,
--     customer_id,
--     plan_id,
--     branch_id,
--     status,
--     started_at,
--     current_period_start,
--     current_period_end,
--     next_billing_date,
--     currency,
--     cancelled_at,
--     ended_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO subscription.subscriptions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

