-- SubscriptionPlanLine Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the subscription.subscription_plan_lines table.
-- Customize this file to add your initial data.

-- INSERT INTO subscription.subscription_plan_lines (
--     id,
--     plan_id,
--     item_id,
--     account_id,
--     description,
--     quantity,
--     unit_price,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO subscription.subscription_plan_lines (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

