-- Migration: Create subscription_plan_lines table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS subscription;

CREATE TABLE IF NOT EXISTS subscription.subscription_plan_lines (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    plan_id UUID NOT NULL,
    item_id UUID NOT NULL,
    account_id UUID NOT NULL,
    description TEXT,
    quantity NUMERIC(18, 4) NOT NULL CHECK (quantity >= 0),
    unit_price NUMERIC(18, 2) NOT NULL CHECK (unit_price >= 0),
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_subscription_plan_lines_plan_id ON subscription.subscription_plan_lines (plan_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_subscription_plan_lines_metadata_gin ON subscription.subscription_plan_lines USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_subscription_plan_lines_metadata_deleted_at ON subscription.subscription_plan_lines ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_subscription_plan_lines_metadata_created_at ON subscription.subscription_plan_lines ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_subscription_plan_lines_metadata_updated_at ON subscription.subscription_plan_lines ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION subscription.subscription_plan_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscription_plan_lines_insert_audit ON subscription.subscription_plan_lines;
CREATE TRIGGER subscription_plan_lines_insert_audit BEFORE INSERT ON subscription.subscription_plan_lines
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plan_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscription_plan_lines_update_audit ON subscription.subscription_plan_lines;
CREATE TRIGGER subscription_plan_lines_update_audit BEFORE UPDATE ON subscription.subscription_plan_lines
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plan_lines_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE subscription.subscription_plan_lines ADD CONSTRAINT fk_subscription_plan_lines_plan_id FOREIGN KEY (plan_id) REFERENCES subscription.subscription_plans (id);
