-- Migration: Create subscription_plans table
-- Generated by metaphor-schema

-- Create billing_cycle enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'billing_cycle') THEN
        CREATE TYPE billing_cycle AS ENUM ('daily', 'weekly', 'monthly', 'quarterly', 'yearly');
    END IF;
END
$$;

-- Create subscription_plan_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscription_plan_status') THEN
        CREATE TYPE subscription_plan_status AS ENUM ('active', 'archived');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS subscription;

CREATE TABLE IF NOT EXISTS subscription.subscription_plans (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    plan_code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    company_id UUID NOT NULL,
    billing_cycle billing_cycle NOT NULL DEFAULT 'monthly',
    billing_day INTEGER NOT NULL DEFAULT 1,
    currency TEXT NOT NULL DEFAULT 'IDR',
    receivable_account_id UUID NOT NULL,
    price NUMERIC(18, 2) NOT NULL CHECK (price >= 0),
    trial_days INTEGER CHECK (trial_days >= 0),
    status subscription_plan_status NOT NULL DEFAULT 'active',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_plans_plan_code ON subscription.subscription_plans (plan_code) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_subscription_plans_company_id_status ON subscription.subscription_plans (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_subscription_plans_metadata_gin ON subscription.subscription_plans USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_subscription_plans_metadata_deleted_at ON subscription.subscription_plans ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_subscription_plans_metadata_created_at ON subscription.subscription_plans ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_subscription_plans_metadata_updated_at ON subscription.subscription_plans ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION subscription.subscription_plans_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscription_plans_insert_audit ON subscription.subscription_plans;
CREATE TRIGGER subscription_plans_insert_audit BEFORE INSERT ON subscription.subscription_plans
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plans_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscription_plans_update_audit ON subscription.subscription_plans;
CREATE TRIGGER subscription_plans_update_audit BEFORE UPDATE ON subscription.subscription_plans
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plans_audit_timestamp();
