-- Migration: Create subscription_billing_runs table
-- Generated by metaphor-schema

-- Create billing_run_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'billing_run_status') THEN
        CREATE TYPE billing_run_status AS ENUM ('pending', 'invoiced', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS subscription;

CREATE TABLE IF NOT EXISTS subscription.subscription_billing_runs (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    subscription_id UUID NOT NULL,
    company_id UUID NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    due_date DATE NOT NULL,
    grand_total NUMERIC(18, 2) NOT NULL CHECK (grand_total >= 0),
    status billing_run_status NOT NULL DEFAULT 'pending',
    invoice_id UUID,
    idempotency_key TEXT NOT NULL,
    attempted_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_billing_runs_subscription_id_period_start ON subscription.subscription_billing_runs (subscription_id, period_start) WHERE (metadata->>'deleted_at') IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscription_billing_runs_idempotency_key ON subscription.subscription_billing_runs (idempotency_key);

CREATE INDEX IF NOT EXISTS idx_subscription_billing_runs_company_id_status ON subscription.subscription_billing_runs (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_subscription_billing_runs_metadata_gin ON subscription.subscription_billing_runs USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_subscription_billing_runs_metadata_deleted_at ON subscription.subscription_billing_runs ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_subscription_billing_runs_metadata_created_at ON subscription.subscription_billing_runs ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_subscription_billing_runs_metadata_updated_at ON subscription.subscription_billing_runs ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION subscription.subscription_billing_runs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscription_billing_runs_insert_audit ON subscription.subscription_billing_runs;
CREATE TRIGGER subscription_billing_runs_insert_audit BEFORE INSERT ON subscription.subscription_billing_runs
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_billing_runs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscription_billing_runs_update_audit ON subscription.subscription_billing_runs;
CREATE TRIGGER subscription_billing_runs_update_audit BEFORE UPDATE ON subscription.subscription_billing_runs
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_billing_runs_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE subscription.subscription_billing_runs ADD CONSTRAINT fk_subscription_billing_runs_subscription_id FOREIGN KEY (subscription_id) REFERENCES subscription.subscriptions (id);
