-- Enum types for subscription module
-- Generated by metaphor-schema

-- Create subscription_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscription_status') THEN
        CREATE TYPE subscription_status AS ENUM ('trial', 'active', 'paused', 'past_due', 'cancelled', 'expired');
    END IF;
END
$$;

-- Create billing_run_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'billing_run_status') THEN
        CREATE TYPE billing_run_status AS ENUM ('pending', 'invoiced', 'failed');
    END IF;
END
$$;

-- Create billing_cycle enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'billing_cycle') THEN
        CREATE TYPE billing_cycle AS ENUM ('daily', 'weekly', 'monthly', 'quarterly', 'yearly');
    END IF;
END
$$;

-- Create subscription_plan_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscription_plan_status') THEN
        CREATE TYPE subscription_plan_status AS ENUM ('active', 'archived');
    END IF;
END
$$;

