-- Company fence posture for subscription module (ADR-0014: strict)
-- Every company-scoped entity here carries company_id and is fenced strict: a session
-- sees only rows whose company_id equals the request-scoped company
-- (`set_config('app.company_id', <uuid>, true)`); an unset var sees zero rows
-- (fail-closed). The tables below were fenced by the ADR-0008-era RLS migrations with
-- this same predicate and policy names; this migration declares the posture (ADR-0014)
-- and re-states each policy verbatim — an idempotent refresh, not a semantic change.
-- Tables without company_id (global reference masters, parent-scoped children) are
-- implicitly outside the declaration and keep their existing posture.
-- Requires the app to connect as a non-superuser role; migrations/seeders run as
-- the owner and bypass.

-- Migration: company row-level-security fence for subscription.subscription_billing_runs
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE subscription.subscription_billing_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription.subscription_billing_runs FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS subscription_billing_runs_company_isolation ON subscription.subscription_billing_runs;
CREATE POLICY subscription_billing_runs_company_isolation ON subscription.subscription_billing_runs
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for subscription.subscription_plans
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE subscription.subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription.subscription_plans FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS subscription_plans_company_isolation ON subscription.subscription_plans;
CREATE POLICY subscription_plans_company_isolation ON subscription.subscription_plans
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for subscription.subscriptions
-- Generated by metaphor-schema (ADR-0014). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE subscription.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription.subscriptions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS subscriptions_company_isolation ON subscription.subscriptions;
CREATE POLICY subscriptions_company_isolation ON subscription.subscriptions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

