-- Audit Triggers Migration for subscription module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Subscription (subscription.subscriptions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION subscription.subscriptions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscriptions_insert_audit ON subscription.subscriptions;
CREATE TRIGGER subscriptions_insert_audit BEFORE INSERT ON subscription.subscriptions
    FOR EACH ROW EXECUTE FUNCTION subscription.subscriptions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscriptions_update_audit ON subscription.subscriptions;
CREATE TRIGGER subscriptions_update_audit BEFORE UPDATE ON subscription.subscriptions
    FOR EACH ROW EXECUTE FUNCTION subscription.subscriptions_audit_timestamp();

-- ==============================================================================
-- Table: SubscriptionBillingRun (subscription.subscription_billing_runs)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION subscription.subscription_billing_runs_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscription_billing_runs_insert_audit ON subscription.subscription_billing_runs;
CREATE TRIGGER subscription_billing_runs_insert_audit BEFORE INSERT ON subscription.subscription_billing_runs
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_billing_runs_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscription_billing_runs_update_audit ON subscription.subscription_billing_runs;
CREATE TRIGGER subscription_billing_runs_update_audit BEFORE UPDATE ON subscription.subscription_billing_runs
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_billing_runs_audit_timestamp();

-- ==============================================================================
-- Table: SubscriptionPlan (subscription.subscription_plans)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION subscription.subscription_plans_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscription_plans_insert_audit ON subscription.subscription_plans;
CREATE TRIGGER subscription_plans_insert_audit BEFORE INSERT ON subscription.subscription_plans
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plans_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscription_plans_update_audit ON subscription.subscription_plans;
CREATE TRIGGER subscription_plans_update_audit BEFORE UPDATE ON subscription.subscription_plans
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plans_audit_timestamp();

-- ==============================================================================
-- Table: SubscriptionPlanLine (subscription.subscription_plan_lines)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION subscription.subscription_plan_lines_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscription_plan_lines_insert_audit ON subscription.subscription_plan_lines;
CREATE TRIGGER subscription_plan_lines_insert_audit BEFORE INSERT ON subscription.subscription_plan_lines
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plan_lines_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscription_plan_lines_update_audit ON subscription.subscription_plan_lines;
CREATE TRIGGER subscription_plan_lines_update_audit BEFORE UPDATE ON subscription.subscription_plan_lines
    FOR EACH ROW EXECUTE FUNCTION subscription.subscription_plan_lines_audit_timestamp();

