-- Migration: Create subscriptions table
-- Generated by metaphor-schema

-- Create subscription_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'subscription_status') THEN
        CREATE TYPE subscription_status AS ENUM ('trial', 'active', 'paused', 'past_due', 'cancelled', 'expired');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS subscription;

CREATE TABLE IF NOT EXISTS subscription.subscriptions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    subscription_number TEXT NOT NULL,
    company_id UUID NOT NULL,
    customer_id UUID NOT NULL,
    plan_id UUID NOT NULL,
    branch_id UUID,
    status subscription_status NOT NULL DEFAULT 'active',
    started_at DATE NOT NULL,
    current_period_start DATE NOT NULL,
    current_period_end DATE NOT NULL,
    next_billing_date DATE NOT NULL,
    currency TEXT NOT NULL DEFAULT 'IDR',
    cancelled_at DATE,
    ended_at DATE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_subscriptions_subscription_number ON subscription.subscriptions (subscription_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_subscriptions_company_id_customer_id_status ON subscription.subscriptions (company_id, customer_id, status);

CREATE INDEX IF NOT EXISTS idx_subscriptions_due ON subscription.subscriptions (status, next_billing_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_subscriptions_metadata_gin ON subscription.subscriptions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_subscriptions_metadata_deleted_at ON subscription.subscriptions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_subscriptions_metadata_created_at ON subscription.subscriptions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_subscriptions_metadata_updated_at ON subscription.subscriptions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION subscription.subscriptions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS subscriptions_insert_audit ON subscription.subscriptions;
CREATE TRIGGER subscriptions_insert_audit BEFORE INSERT ON subscription.subscriptions
    FOR EACH ROW EXECUTE FUNCTION subscription.subscriptions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS subscriptions_update_audit ON subscription.subscriptions;
CREATE TRIGGER subscriptions_update_audit BEFORE UPDATE ON subscription.subscriptions
    FOR EACH ROW EXECUTE FUNCTION subscription.subscriptions_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE subscription.subscriptions ADD CONSTRAINT fk_subscriptions_plan_id FOREIGN KEY (plan_id) REFERENCES subscription.subscription_plans (id);
