//! Domain events for Subscription entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Subscription;

/// Domain events for Subscription — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Subscription>)` variant.
pub type SubscriptionEvent = CrudEvent<Subscription>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Subscription events.
pub type SubscriptionEventPublisher = Arc<dyn CrudEventPublisher<Subscription> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSubscriptionEventPublisher = NoOpCrudEventPublisher<Subscription>;
