//! Domain events for SubscriptionPlanLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SubscriptionPlanLine;

/// Domain events for SubscriptionPlanLine — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SubscriptionPlanLine>)` variant.
pub type SubscriptionPlanLineEvent = CrudEvent<SubscriptionPlanLine>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SubscriptionPlanLine events.
pub type SubscriptionPlanLineEventPublisher = Arc<dyn CrudEventPublisher<SubscriptionPlanLine> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSubscriptionPlanLineEventPublisher = NoOpCrudEventPublisher<SubscriptionPlanLine>;
