//! Domain events for SubscriptionPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SubscriptionPlan;

/// Domain events for SubscriptionPlan — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SubscriptionPlan>)` variant.
pub type SubscriptionPlanEvent = CrudEvent<SubscriptionPlan>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SubscriptionPlan events.
pub type SubscriptionPlanEventPublisher = Arc<dyn CrudEventPublisher<SubscriptionPlan> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSubscriptionPlanEventPublisher = NoOpCrudEventPublisher<SubscriptionPlan>;
