//! Domain events for SubscriptionBillingRun entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SubscriptionBillingRun;

/// Domain events for SubscriptionBillingRun — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SubscriptionBillingRun>)` variant.
pub type SubscriptionBillingRunEvent = CrudEvent<SubscriptionBillingRun>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SubscriptionBillingRun events.
pub type SubscriptionBillingRunEventPublisher = Arc<dyn CrudEventPublisher<SubscriptionBillingRun> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSubscriptionBillingRunEventPublisher = NoOpCrudEventPublisher<SubscriptionBillingRun>;
