//! Event handler trait for SubscriptionPlan events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SubscriptionPlanEvent;

/// Event handler for SubscriptionPlan events.
/// Implement this trait to react to SubscriptionPlan lifecycle events.
pub trait SubscriptionPlanEventHandler: EventHandler<SubscriptionPlanEvent> {}
