//! Event handler trait for Subscription events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SubscriptionEvent;

/// Event handler for Subscription events.
/// Implement this trait to react to Subscription lifecycle events.
pub trait SubscriptionEventHandler: EventHandler<SubscriptionEvent> {}
