//! Event handler trait for SubscriptionBillingRun events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SubscriptionBillingRunEvent;

/// Event handler for SubscriptionBillingRun events.
/// Implement this trait to react to SubscriptionBillingRun lifecycle events.
pub trait SubscriptionBillingRunEventHandler: EventHandler<SubscriptionBillingRunEvent> {}
