//! Event handler trait for SubscriptionPlanLine events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SubscriptionPlanLineEvent;

/// Event handler for SubscriptionPlanLine events.
/// Implement this trait to react to SubscriptionPlanLine lifecycle events.
pub trait SubscriptionPlanLineEventHandler: EventHandler<SubscriptionPlanLineEvent> {}
