//! Event subscriber type aliases for Subscription module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::SubscriptionEvent;
use crate::domain::event::SubscriptionBillingRunEvent;
use crate::domain::event::SubscriptionPlanEvent;
use crate::domain::event::SubscriptionPlanLineEvent;

/// Subscriber for Subscription events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SubscriptionEventSubscriber = GenericEventSubscriber<SubscriptionEvent>;

/// Subscriber for SubscriptionBillingRun events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SubscriptionBillingRunEventSubscriber = GenericEventSubscriber<SubscriptionBillingRunEvent>;

/// Subscriber for SubscriptionPlan events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SubscriptionPlanEventSubscriber = GenericEventSubscriber<SubscriptionPlanEvent>;

/// Subscriber for SubscriptionPlanLine events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type SubscriptionPlanLineEventSubscriber = GenericEventSubscriber<SubscriptionPlanLineEvent>;

// <<< CUSTOM
// END CUSTOM
