//! SubscriptionPlanLine seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SubscriptionPlanLine data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SUBSCRIPTIONPLANLINE SEEDER
// ============================================================================

/// Seeder for subscription_plan_line
pub struct SeedSubscriptionPlanLineSeeder;

impl SeedSubscriptionPlanLineSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSubscriptionPlanLineSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSubscriptionPlanLineSeeder {
    fn name(&self) -> &'static str {
        "SeedSubscriptionPlanLineSeeder"
    }

    fn order(&self) -> i32 {
        4
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if subscription.subscription_plan_lines table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM subscription.subscription_plan_lines")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/subscription_plan_line_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM subscription.subscription_plan_lines")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

