//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod subscription_repository;
pub mod subscription_billing_run_repository;
pub mod subscription_plan_repository;
pub mod subscription_plan_line_repository;

// Re-exports
pub use subscription_repository::{
    SubscriptionRepository,
    SubscriptionPaginationParams,
    SubscriptionPaginatedResult,
    SubscriptionFilter,
};
pub use subscription_billing_run_repository::{
    SubscriptionBillingRunRepository,
    SubscriptionBillingRunPaginationParams,
    SubscriptionBillingRunPaginatedResult,
    SubscriptionBillingRunFilter,
};
pub use subscription_plan_repository::{
    SubscriptionPlanRepository,
    SubscriptionPlanPaginationParams,
    SubscriptionPlanPaginatedResult,
    SubscriptionPlanFilter,
};
pub use subscription_plan_line_repository::{
    SubscriptionPlanLineRepository,
    SubscriptionPlanLinePaginationParams,
    SubscriptionPlanLinePaginatedResult,
    SubscriptionPlanLineFilter,
};
