//! Repository trait for SubscriptionPlanLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SubscriptionPlanLine aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SubscriptionPlanLine;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionPlanLinePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SubscriptionPlanLinePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SubscriptionPlanLinePaginatedResult {
    pub data: Vec<SubscriptionPlanLine>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionPlanLineFilter {
    pub plan_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub account_id: Option<Uuid>,
    pub description: Option<String>,
}

impl SubscriptionPlanLineFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.plan_id.is_some() || self.item_id.is_some() || self.account_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for SubscriptionPlanLine aggregate
///
/// This trait defines the persistence contract for SubscriptionPlanLine entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SubscriptionPlanLineRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new subscription_plan_line entity
    async fn save(&self, entity: &SubscriptionPlanLine) -> Result<SubscriptionPlanLine>;

    /// Find subscription_plan_line by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SubscriptionPlanLine>>;

    /// Find all subscription_plan_line entities
    async fn find_all(&self) -> Result<Vec<SubscriptionPlanLine>>;

    /// Update subscription_plan_line by ID
    async fn update(&self, id: &str, entity: &SubscriptionPlanLine) -> Result<Option<SubscriptionPlanLine>>;

    /// Delete subscription_plan_line by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List subscription_plan_line with pagination
    async fn list(&self, params: SubscriptionPlanLinePaginationParams) -> Result<SubscriptionPlanLinePaginatedResult>;

    /// List subscription_plan_line with pagination and filters
    async fn list_with_filters(&self, params: SubscriptionPlanLinePaginationParams, filters: SubscriptionPlanLineFilter) -> Result<SubscriptionPlanLinePaginatedResult>;

    /// Count all subscription_plan_line entities
    async fn count(&self) -> Result<u64>;

    /// Count subscription_plan_line entities matching filters
    async fn count_with_filters(&self, filters: SubscriptionPlanLineFilter) -> Result<u64>;

    /// Check if subscription_plan_line exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete subscription_plan_line by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted subscription_plan_line by ID
    async fn restore(&self, id: &str) -> Result<Option<SubscriptionPlanLine>>;

    /// List soft-deleted subscription_plan_line entities
    async fn list_deleted(&self, params: SubscriptionPlanLinePaginationParams) -> Result<SubscriptionPlanLinePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save subscription_plan_line entities
    async fn bulk_save(&self, entities: &[SubscriptionPlanLine]) -> Result<Vec<SubscriptionPlanLine>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
