//! Repository trait for SubscriptionBillingRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SubscriptionBillingRun aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{SubscriptionBillingRun, BillingRunStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionBillingRunPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SubscriptionBillingRunPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SubscriptionBillingRunPaginatedResult {
    pub data: Vec<SubscriptionBillingRun>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionBillingRunFilter {
    pub subscription_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub status: Option<BillingRunStatus>,
    pub invoice_id: Option<Uuid>,
    pub idempotency_key: Option<String>,
}

impl SubscriptionBillingRunFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.subscription_id.is_some() || self.company_id.is_some() || self.status.is_some() || self.invoice_id.is_some() || self.idempotency_key.is_some()
    }
}

/// Repository trait for SubscriptionBillingRun aggregate
///
/// This trait defines the persistence contract for SubscriptionBillingRun entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SubscriptionBillingRunRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new subscription_billing_run entity
    async fn save(&self, entity: &SubscriptionBillingRun) -> Result<SubscriptionBillingRun>;

    /// Find subscription_billing_run by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SubscriptionBillingRun>>;

    /// Find all subscription_billing_run entities
    async fn find_all(&self) -> Result<Vec<SubscriptionBillingRun>>;

    /// Update subscription_billing_run by ID
    async fn update(&self, id: &str, entity: &SubscriptionBillingRun) -> Result<Option<SubscriptionBillingRun>>;

    /// Delete subscription_billing_run by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List subscription_billing_run with pagination
    async fn list(&self, params: SubscriptionBillingRunPaginationParams) -> Result<SubscriptionBillingRunPaginatedResult>;

    /// List subscription_billing_run with pagination and filters
    async fn list_with_filters(&self, params: SubscriptionBillingRunPaginationParams, filters: SubscriptionBillingRunFilter) -> Result<SubscriptionBillingRunPaginatedResult>;

    /// Count all subscription_billing_run entities
    async fn count(&self) -> Result<u64>;

    /// Count subscription_billing_run entities matching filters
    async fn count_with_filters(&self, filters: SubscriptionBillingRunFilter) -> Result<u64>;

    /// Check if subscription_billing_run exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete subscription_billing_run by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted subscription_billing_run by ID
    async fn restore(&self, id: &str) -> Result<Option<SubscriptionBillingRun>>;

    /// List soft-deleted subscription_billing_run entities
    async fn list_deleted(&self, params: SubscriptionBillingRunPaginationParams) -> Result<SubscriptionBillingRunPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save subscription_billing_run entities
    async fn bulk_save(&self, entities: &[SubscriptionBillingRun]) -> Result<Vec<SubscriptionBillingRun>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
