//! Repository trait for SubscriptionPlan aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SubscriptionPlan aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{SubscriptionPlan, BillingCycle, SubscriptionPlanStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionPlanPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SubscriptionPlanPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SubscriptionPlanPaginatedResult {
    pub data: Vec<SubscriptionPlan>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionPlanFilter {
    pub plan_code: Option<String>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub company_id: Option<Uuid>,
    pub billing_cycle: Option<BillingCycle>,
    pub currency: Option<String>,
    pub receivable_account_id: Option<Uuid>,
    pub status: Option<SubscriptionPlanStatus>,
}

impl SubscriptionPlanFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.plan_code.is_some() || self.name.is_some() || self.description.is_some() || self.company_id.is_some() || self.billing_cycle.is_some() || self.currency.is_some() || self.receivable_account_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for SubscriptionPlan aggregate
///
/// This trait defines the persistence contract for SubscriptionPlan entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SubscriptionPlanRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new subscription_plan entity
    async fn save(&self, entity: &SubscriptionPlan) -> Result<SubscriptionPlan>;

    /// Find subscription_plan by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SubscriptionPlan>>;

    /// Find all subscription_plan entities
    async fn find_all(&self) -> Result<Vec<SubscriptionPlan>>;

    /// Update subscription_plan by ID
    async fn update(&self, id: &str, entity: &SubscriptionPlan) -> Result<Option<SubscriptionPlan>>;

    /// Delete subscription_plan by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List subscription_plan with pagination
    async fn list(&self, params: SubscriptionPlanPaginationParams) -> Result<SubscriptionPlanPaginatedResult>;

    /// List subscription_plan with pagination and filters
    async fn list_with_filters(&self, params: SubscriptionPlanPaginationParams, filters: SubscriptionPlanFilter) -> Result<SubscriptionPlanPaginatedResult>;

    /// Count all subscription_plan entities
    async fn count(&self) -> Result<u64>;

    /// Count subscription_plan entities matching filters
    async fn count_with_filters(&self, filters: SubscriptionPlanFilter) -> Result<u64>;

    /// Check if subscription_plan exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete subscription_plan by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted subscription_plan by ID
    async fn restore(&self, id: &str) -> Result<Option<SubscriptionPlan>>;

    /// List soft-deleted subscription_plan entities
    async fn list_deleted(&self, params: SubscriptionPlanPaginationParams) -> Result<SubscriptionPlanPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save subscription_plan entities
    async fn bulk_save(&self, entities: &[SubscriptionPlan]) -> Result<Vec<SubscriptionPlan>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
