//! Repository trait for Subscription aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Subscription aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Subscription, SubscriptionStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SubscriptionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SubscriptionPaginatedResult {
    pub data: Vec<Subscription>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SubscriptionFilter {
    pub subscription_number: Option<String>,
    pub customer_id: Option<Uuid>,
    pub plan_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub status: Option<SubscriptionStatus>,
    pub currency: Option<String>,
}

impl SubscriptionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.subscription_number.is_some() || self.customer_id.is_some() || self.plan_id.is_some() || self.branch_id.is_some() || self.status.is_some() || self.currency.is_some()
    }
}

/// Repository trait for Subscription aggregate
///
/// This trait defines the persistence contract for Subscription entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SubscriptionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new subscription entity
    async fn save(&self, entity: &Subscription) -> Result<Subscription>;

    /// Find subscription by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Subscription>>;

    /// Find all subscription entities
    async fn find_all(&self) -> Result<Vec<Subscription>>;

    /// Update subscription by ID
    async fn update(&self, id: &str, entity: &Subscription) -> Result<Option<Subscription>>;

    /// Delete subscription by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List subscription with pagination
    async fn list(&self, params: SubscriptionPaginationParams) -> Result<SubscriptionPaginatedResult>;

    /// List subscription with pagination and filters
    async fn list_with_filters(&self, params: SubscriptionPaginationParams, filters: SubscriptionFilter) -> Result<SubscriptionPaginatedResult>;

    /// Count all subscription entities
    async fn count(&self) -> Result<u64>;

    /// Count subscription entities matching filters
    async fn count_with_filters(&self, filters: SubscriptionFilter) -> Result<u64>;

    /// Check if subscription exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete subscription by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted subscription by ID
    async fn restore(&self, id: &str) -> Result<Option<Subscription>>;

    /// List soft-deleted subscription entities
    async fn list_deleted(&self, params: SubscriptionPaginationParams) -> Result<SubscriptionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save subscription entities
    async fn bulk_save(&self, entities: &[Subscription]) -> Result<Vec<Subscription>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
