//! Repository for SubscriptionPlanLine entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SubscriptionPlanLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SubscriptionPlanLine;

/// Table name for SubscriptionPlanLine entities
pub const TABLE_NAME: &str = "subscription.subscription_plan_lines";

/// Repository for SubscriptionPlanLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubscriptionPlanLineRepository(
    backbone_orm::GenericCrudRepository<SubscriptionPlanLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubscriptionPlanLineRepository {
    type Target = backbone_orm::GenericCrudRepository<SubscriptionPlanLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubscriptionPlanLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SubscriptionPlanLineRepository, SubscriptionPlanLine, soft_delete);
