//! Repository for SubscriptionPlanLine entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the cadence's blueprint read (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SubscriptionPlanLine, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{FromRow, PgPool};
use uuid::Uuid;

use crate::domain::entity::SubscriptionPlanLine;

/// Table name for SubscriptionPlanLine entities
pub const TABLE_NAME: &str = "subscription.subscription_plan_lines";

/// Repository for SubscriptionPlanLine entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubscriptionPlanLineRepository(
    backbone_orm::GenericCrudRepository<SubscriptionPlanLine, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubscriptionPlanLineRepository {
    type Target = backbone_orm::GenericCrudRepository<SubscriptionPlanLine, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubscriptionPlanLineRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One plan's invoice blueprint line (the cadence reads these to build the due event).
#[derive(FromRow)]
pub struct PlanLineRow {
    pub item_id: Uuid,
    pub account_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
}

/// Cadence blueprint SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl SubscriptionPlanLineRepository {
    /// A plan's live blueprint lines. Read via the bare pool the caller supplies — the cadence sweep
    /// is cross-company (see `SubscriptionRepository::find_due_plans`).
    pub async fn find_blueprint_by_plan(
        &self,
        pool: &PgPool,
        plan_id: Uuid,
    ) -> Result<Vec<PlanLineRow>, sqlx::Error> {
        sqlx::query_as::<_, PlanLineRow>(
            r#"SELECT item_id, account_id, description, quantity, unit_price
               FROM subscription.subscription_plan_lines
               WHERE plan_id = $1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(plan_id)
        .fetch_all(pool).await
    }
}

backbone_core::impl_crud_repository!(SubscriptionPlanLineRepository, SubscriptionPlanLine, soft_delete);
