//! Repository for SubscriptionBillingRun entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom method
//! below holds the cadence's billing-run insert (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SubscriptionBillingRun, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use rust_decimal::Decimal;
use sqlx::{PgConnection, PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::SubscriptionBillingRun;

/// Table name for SubscriptionBillingRun entities
pub const TABLE_NAME: &str = "subscription.subscription_billing_runs";

/// Repository for SubscriptionBillingRun entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubscriptionBillingRunRepository(
    backbone_orm::GenericCrudRepository<SubscriptionBillingRun, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubscriptionBillingRunRepository {
    type Target = backbone_orm::GenericCrudRepository<SubscriptionBillingRun, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubscriptionBillingRunRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row the cadence inserts for a due subscription's billing run.
pub struct NewBillingRunRow {
    pub id: Uuid,
    pub subscription_id: Uuid,
    pub company_id: Uuid,
    pub period_start: NaiveDate,
    pub period_end: NaiveDate,
    pub due_date: NaiveDate,
    pub grand_total: Decimal,
    pub idempotency_key: String,
}

/// Cadence billing-run SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl SubscriptionBillingRunRepository {
    /// Exactly one billing run per (subscription, period): `ON CONFLICT (subscription_id, period_start)
    /// DO NOTHING RETURNING id`. Returns the id when THIS caller created the run (the winner), or
    /// `None` when a run already existed (a re-tick). Takes the CALLER'S connection (company already
    /// bound) so the run + the period advance + the outbox event commit as one unit.
    pub async fn insert_pending_run_on_conflict_nothing(
        &self,
        conn: &mut PgConnection,
        r: &NewBillingRunRow,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = sqlx::query(
            r#"INSERT INTO subscription.subscription_billing_runs
                 (id, subscription_id, company_id, period_start, period_end, due_date,
                  grand_total, status, idempotency_key)
               VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending'::billing_run_status, $8)
               ON CONFLICT (subscription_id, period_start) WHERE (metadata->>'deleted_at') IS NULL
               DO NOTHING RETURNING id"#,
        )
        .bind(r.id).bind(r.subscription_id).bind(r.company_id)
        .bind(r.period_start).bind(r.period_end).bind(r.due_date)
        .bind(r.grand_total).bind(&r.idempotency_key)
        .fetch_optional(conn).await?;
        Ok(row.map(|r| r.get("id")))
    }
}

backbone_core::impl_crud_repository!(SubscriptionBillingRunRepository, SubscriptionBillingRun, soft_delete);
