//! Repository for Subscription entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the cadence's subscription SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Subscription, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use chrono::NaiveDate;
use sqlx::{FromRow, PgConnection, PgPool};
use uuid::Uuid;

use crate::domain::entity::Subscription;

/// Table name for Subscription entities
pub const TABLE_NAME: &str = "subscription.subscriptions";

/// Repository for Subscription entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SubscriptionRepository(
    backbone_orm::GenericCrudRepository<Subscription, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SubscriptionRepository {
    type Target = backbone_orm::GenericCrudRepository<Subscription, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SubscriptionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One due subscription joined with its plan (the cadence sweep read).
#[derive(FromRow)]
pub struct DuePlanRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub customer_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub plan_id: Uuid,
    pub next_billing_date: NaiveDate,
    pub currency: String,
    pub billing_cycle: String,
    pub receivable_account_id: Uuid,
}

/// Cadence + period-advance SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl SubscriptionRepository {
    /// Every active subscription whose `next_billing_date` has arrived, joined to its plan.
    ///
    /// This is the cadence sweep — it intentionally spans ALL companies (the cron bills every
    /// tenant's due subscriptions in one tick), so it reads via the bare pool the caller supplies and
    /// is NOT company-scoped. Under RLS (ADR-0008) the composing service MUST drive `process_due`
    /// from a system / cross-company role, otherwise the fence returns 0 rows and nobody is billed.
    /// The bare read is the historical behaviour, preserved on purpose; the role decision is the
    /// composition layer's, not this module's.
    pub async fn find_due_plans(
        &self,
        pool: &PgPool,
        today: NaiveDate,
    ) -> Result<Vec<DuePlanRow>, sqlx::Error> {
        sqlx::query_as::<_, DuePlanRow>(
            r#"SELECT s.id, s.company_id, s.customer_id, s.branch_id, s.plan_id,
                      s.next_billing_date, s.currency,
                      p.billing_cycle::text AS billing_cycle, p.receivable_account_id
               FROM subscription.subscriptions s
               JOIN subscription.subscription_plans p ON s.plan_id = p.id
               WHERE s.status = 'active' AND s.next_billing_date <= $1
                 AND (s.metadata->>'deleted_at') IS NULL"#,
        )
        .bind(today)
        .fetch_all(pool).await
    }

    /// Advance a subscription's billing period on the caller's tx.
    ///
    /// `WHERE next_billing_date = expected_next` so a concurrent tick that already advanced it
    /// misses (rows_affected == 0 ⇒ idempotent no-op). Takes the CALLER'S connection so the advance,
    /// the billing-run insert, and the outbox event commit as one unit; the caller has already bound
    /// the company on `conn` — don't re-bind here.
    pub async fn advance_period(
        &self,
        conn: &mut PgConnection,
        id: Uuid,
        period_start: NaiveDate,
        period_end: NaiveDate,
        new_next: NaiveDate,
        expected_next: NaiveDate,
    ) -> Result<u64, sqlx::Error> {
        sqlx::query(
            r#"UPDATE subscription.subscriptions
                 SET current_period_start = $2, current_period_end = $3, next_billing_date = $4
               WHERE id = $1 AND next_billing_date = $5 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(id).bind(period_start).bind(period_end).bind(new_next).bind(expected_next)
        .execute(conn).await.map(|r| r.rows_affected())
    }
}

backbone_core::impl_crud_repository!(SubscriptionRepository, Subscription, soft_delete);
