//! Validator for SubscriptionBillingRun entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SubscriptionBillingRun>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::SubscriptionBillingRun;

/// Validator type alias for SubscriptionBillingRun entities.
pub type SubscriptionBillingRunValidator = EntityValidator<SubscriptionBillingRun>;

/// Build a validator for SubscriptionBillingRun with all schema-defined field rules.
pub fn subscription_billing_run_validator() -> SubscriptionBillingRunValidator {
    EntityValidator::new()
        .rule(RequiredString::new("idempotency_key", |e: &SubscriptionBillingRun| &e.idempotency_key))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
