//! Validator for Subscription entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Subscription>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::Subscription;

/// Validator type alias for Subscription entities.
pub type SubscriptionValidator = EntityValidator<Subscription>;

/// Build a validator for Subscription with all schema-defined field rules.
pub fn subscription_validator() -> SubscriptionValidator {
    EntityValidator::new()
        .rule(RequiredString::new("subscription_number", |e: &Subscription| &e.subscription_number))
        .rule(RequiredString::new("currency", |e: &Subscription| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
