//! Validator for SubscriptionPlanLine entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SubscriptionPlanLine>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::SubscriptionPlanLine;

/// Validator type alias for SubscriptionPlanLine entities.
pub type SubscriptionPlanLineValidator = EntityValidator<SubscriptionPlanLine>;

/// Build a validator for SubscriptionPlanLine with all schema-defined field rules.
pub fn subscription_plan_line_validator() -> SubscriptionPlanLineValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("description", |e: &SubscriptionPlanLine| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
