//! Validator for SubscriptionPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SubscriptionPlan>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::SubscriptionPlan;

/// Validator type alias for SubscriptionPlan entities.
pub type SubscriptionPlanValidator = EntityValidator<SubscriptionPlan>;

/// Build a validator for SubscriptionPlan with all schema-defined field rules.
pub fn subscription_plan_validator() -> SubscriptionPlanValidator {
    EntityValidator::new()
        .rule(RequiredString::new("plan_code", |e: &SubscriptionPlan| &e.plan_code))
        .rule(RequiredString::new("name", |e: &SubscriptionPlan| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &SubscriptionPlan| e.description.as_deref()))
        .rule(RequiredString::new("currency", |e: &SubscriptionPlan| &e.currency))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
