//! Auth configuration for Subscription handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Subscription>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SubscriptionService;
use crate::domain::entity::Subscription;

/// Permission string constants for Subscription operations.
pub mod permissions {
    pub const LIST:        &str = "subscription:list";
    pub const READ:        &str = "subscription:read";
    pub const CREATE:      &str = "subscription:create";
    pub const UPDATE:      &str = "subscription:update";
    pub const DELETE:      &str = "subscription:delete";
    pub const RESTORE:     &str = "subscription:restore";
    pub const TRASH:       &str = "subscription:trash";
    pub const EMPTY_TRASH: &str = "subscription:empty_trash";
    pub const BULK_CREATE: &str = "subscription:bulk_create";
    pub const UPSERT:      &str = "subscription:upsert";
}

/// Resource policy for Subscription — maps CRUD actions to permission strings.
pub struct SubscriptionPolicy;

#[async_trait]
impl ResourcePolicy<Subscription> for SubscriptionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Subscription,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Subscription handlers.
///
/// Wraps `SubscriptionService` and checks `SubscriptionPolicy` before delegating.
pub type SubscriptionGuard = PermissionGuard<Subscription>;

/// Service-integrated permission guard for Subscription (for use in generated handlers).
pub type SubscriptionServiceGuard = ServicePermissionGuard<Subscription, SubscriptionService, SubscriptionPolicy>;

// <<< CUSTOM
// END CUSTOM
