//! Auth configuration for SubscriptionPlan handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SubscriptionPlan>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SubscriptionPlanService;
use crate::domain::entity::SubscriptionPlan;

/// Permission string constants for SubscriptionPlan operations.
pub mod permissions {
    pub const LIST:        &str = "subscription_plan:list";
    pub const READ:        &str = "subscription_plan:read";
    pub const CREATE:      &str = "subscription_plan:create";
    pub const UPDATE:      &str = "subscription_plan:update";
    pub const DELETE:      &str = "subscription_plan:delete";
    pub const RESTORE:     &str = "subscription_plan:restore";
    pub const TRASH:       &str = "subscription_plan:trash";
    pub const EMPTY_TRASH: &str = "subscription_plan:empty_trash";
    pub const BULK_CREATE: &str = "subscription_plan:bulk_create";
    pub const UPSERT:      &str = "subscription_plan:upsert";
}

/// Resource policy for SubscriptionPlan — maps CRUD actions to permission strings.
pub struct SubscriptionPlanPolicy;

#[async_trait]
impl ResourcePolicy<SubscriptionPlan> for SubscriptionPlanPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SubscriptionPlan,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SubscriptionPlan handlers.
///
/// Wraps `SubscriptionPlanService` and checks `SubscriptionPlanPolicy` before delegating.
pub type SubscriptionPlanGuard = PermissionGuard<SubscriptionPlan>;

/// Service-integrated permission guard for SubscriptionPlan (for use in generated handlers).
pub type SubscriptionPlanServiceGuard = ServicePermissionGuard<SubscriptionPlan, SubscriptionPlanService, SubscriptionPlanPolicy>;

// <<< CUSTOM
// END CUSTOM
