//! Auth configuration for SubscriptionPlanLine handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SubscriptionPlanLine>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SubscriptionPlanLineService;
use crate::domain::entity::SubscriptionPlanLine;

/// Permission string constants for SubscriptionPlanLine operations.
pub mod permissions {
    pub const LIST:        &str = "subscription_plan_line:list";
    pub const READ:        &str = "subscription_plan_line:read";
    pub const CREATE:      &str = "subscription_plan_line:create";
    pub const UPDATE:      &str = "subscription_plan_line:update";
    pub const DELETE:      &str = "subscription_plan_line:delete";
    pub const RESTORE:     &str = "subscription_plan_line:restore";
    pub const TRASH:       &str = "subscription_plan_line:trash";
    pub const EMPTY_TRASH: &str = "subscription_plan_line:empty_trash";
    pub const BULK_CREATE: &str = "subscription_plan_line:bulk_create";
    pub const UPSERT:      &str = "subscription_plan_line:upsert";
}

/// Resource policy for SubscriptionPlanLine — maps CRUD actions to permission strings.
pub struct SubscriptionPlanLinePolicy;

#[async_trait]
impl ResourcePolicy<SubscriptionPlanLine> for SubscriptionPlanLinePolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SubscriptionPlanLine,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SubscriptionPlanLine handlers.
///
/// Wraps `SubscriptionPlanLineService` and checks `SubscriptionPlanLinePolicy` before delegating.
pub type SubscriptionPlanLineGuard = PermissionGuard<SubscriptionPlanLine>;

/// Service-integrated permission guard for SubscriptionPlanLine (for use in generated handlers).
pub type SubscriptionPlanLineServiceGuard = ServicePermissionGuard<SubscriptionPlanLine, SubscriptionPlanLineService, SubscriptionPlanLinePolicy>;

// <<< CUSTOM
// END CUSTOM
