//! Auth configuration for SubscriptionBillingRun handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SubscriptionBillingRun>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SubscriptionBillingRunService;
use crate::domain::entity::SubscriptionBillingRun;

/// Permission string constants for SubscriptionBillingRun operations.
pub mod permissions {
    pub const LIST:        &str = "subscription_billing_run:list";
    pub const READ:        &str = "subscription_billing_run:read";
    pub const CREATE:      &str = "subscription_billing_run:create";
    pub const UPDATE:      &str = "subscription_billing_run:update";
    pub const DELETE:      &str = "subscription_billing_run:delete";
    pub const RESTORE:     &str = "subscription_billing_run:restore";
    pub const TRASH:       &str = "subscription_billing_run:trash";
    pub const EMPTY_TRASH: &str = "subscription_billing_run:empty_trash";
    pub const BULK_CREATE: &str = "subscription_billing_run:bulk_create";
    pub const UPSERT:      &str = "subscription_billing_run:upsert";
}

/// Resource policy for SubscriptionBillingRun — maps CRUD actions to permission strings.
pub struct SubscriptionBillingRunPolicy;

#[async_trait]
impl ResourcePolicy<SubscriptionBillingRun> for SubscriptionBillingRunPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SubscriptionBillingRun,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SubscriptionBillingRun handlers.
///
/// Wraps `SubscriptionBillingRunService` and checks `SubscriptionBillingRunPolicy` before delegating.
pub type SubscriptionBillingRunGuard = PermissionGuard<SubscriptionBillingRun>;

/// Service-integrated permission guard for SubscriptionBillingRun (for use in generated handlers).
pub type SubscriptionBillingRunServiceGuard = ServicePermissionGuard<SubscriptionBillingRun, SubscriptionBillingRunService, SubscriptionBillingRunPolicy>;

// <<< CUSTOM
// END CUSTOM
