//! SubscriptionPlan API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SubscriptionPlan CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SUBSCRIPTIONPLAN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SubscriptionPlan
pub struct SubscriptionPlanTestData;

impl TestDataGenerator for SubscriptionPlanTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "plan_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "company_id": Uuid::new_v4().to_string(),
            "billing_cycle": "daily",
            "billing_day": 1,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "receivable_account_id": Uuid::new_v4().to_string(),
            "price": 0,
            "trial_days": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "plan_code": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "company_id": Uuid::new_v4().to_string(),
            "billing_cycle": "daily",
            "billing_day": 1,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "receivable_account_id": Uuid::new_v4().to_string(),
            "price": 0,
            "trial_days": null,
            "status": "active",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SUBSCRIPTIONPLAN API TEST
// ============================================================================

/// SubscriptionPlan API test suite
pub struct SubscriptionPlanApiTest {
    inner: GenericCrudTest<SubscriptionPlanTestData>,
}

impl SubscriptionPlanApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/subscription_plans", "SubscriptionPlan");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SubscriptionPlanTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SubscriptionPlanApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_subscription_plan_crud() {
        let mut test = SubscriptionPlanApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SubscriptionPlan specific tests here
// <<< CUSTOM TESTS END >>>
