//! SubscriptionPlanLine API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SubscriptionPlanLine CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SUBSCRIPTIONPLANLINE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SubscriptionPlanLine
pub struct SubscriptionPlanLineTestData;

impl TestDataGenerator for SubscriptionPlanLineTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "plan_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "account_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "plan_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "account_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/subscription_plans", &super::subscription_plan_api_test::SubscriptionPlanTestData).await {
            deps.push(("plan_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SUBSCRIPTIONPLANLINE API TEST
// ============================================================================

/// SubscriptionPlanLine API test suite
pub struct SubscriptionPlanLineApiTest {
    inner: GenericCrudTest<SubscriptionPlanLineTestData>,
}

impl SubscriptionPlanLineApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/subscription_plan_lines", "SubscriptionPlanLine");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SubscriptionPlanLineTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SubscriptionPlanLineApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_subscription_plan_line_crud() {
        let mut test = SubscriptionPlanLineApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SubscriptionPlanLine specific tests here
// <<< CUSTOM TESTS END >>>
