//! Subscription API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Subscription CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SUBSCRIPTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Subscription
pub struct SubscriptionTestData;

impl TestDataGenerator for SubscriptionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "subscription_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "customer_id": Uuid::new_v4().to_string(),
            "plan_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "status": "trial",
            "started_at": now,
            "current_period_start": Utc::now().format("%Y-%m-%d").to_string(),
            "current_period_end": Utc::now().format("%Y-%m-%d").to_string(),
            "next_billing_date": Utc::now().format("%Y-%m-%d").to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "cancelled_at": now,
            "ended_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "subscription_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "customer_id": Uuid::new_v4().to_string(),
            "plan_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "status": "trial",
            "started_at": now,
            "current_period_start": Utc::now().format("%Y-%m-%d").to_string(),
            "current_period_end": Utc::now().format("%Y-%m-%d").to_string(),
            "next_billing_date": Utc::now().format("%Y-%m-%d").to_string(),
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "cancelled_at": now,
            "ended_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/subscription_plans", &super::subscription_plan_api_test::SubscriptionPlanTestData).await {
            deps.push(("plan_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SUBSCRIPTION API TEST
// ============================================================================

/// Subscription API test suite
pub struct SubscriptionApiTest {
    inner: GenericCrudTest<SubscriptionTestData>,
}

impl SubscriptionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/subscriptions", "Subscription");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SubscriptionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SubscriptionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_subscription_crud() {
        let mut test = SubscriptionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Subscription specific tests here
// <<< CUSTOM TESTS END >>>
