//! Subscription Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::SubscriptionService;
use crate::application::service::SubscriptionBillingRunService;
use crate::application::service::SubscriptionPlanService;
use crate::application::service::SubscriptionPlanLineService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Subscription service
    pub subscription_service: Arc<SubscriptionService>,
    /// SubscriptionBillingRun service
    pub subscription_billing_run_service: Arc<SubscriptionBillingRunService>,
    /// SubscriptionPlan service
    pub subscription_plan_service: Arc<SubscriptionPlanService>,
    /// SubscriptionPlanLine service
    pub subscription_plan_line_service: Arc<SubscriptionPlanLineService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        subscription_service: Arc<SubscriptionService>,
        subscription_billing_run_service: Arc<SubscriptionBillingRunService>,
        subscription_plan_service: Arc<SubscriptionPlanService>,
        subscription_plan_line_service: Arc<SubscriptionPlanLineService>
    ) -> Self {
        Self {
            subscription_service,
            subscription_billing_run_service,
            subscription_plan_service,
            subscription_plan_line_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::SubscriptionModule) -> Self {
        Self {
            subscription_service: module.subscription_service.clone(),
            subscription_billing_run_service: module.subscription_billing_run_service.clone(),
            subscription_plan_service: module.subscription_plan_service.clone(),
            subscription_plan_line_service: module.subscription_plan_line_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    subscription_service: Option<Arc<SubscriptionService>>,
    subscription_billing_run_service: Option<Arc<SubscriptionBillingRunService>>,
    subscription_plan_service: Option<Arc<SubscriptionPlanService>>,
    subscription_plan_line_service: Option<Arc<SubscriptionPlanLineService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Subscription service.
    pub fn with_subscription_service(mut self, service: Arc<SubscriptionService>) -> Self {
        self.subscription_service = Some(service);
        self
    }

    /// Set the SubscriptionBillingRun service.
    pub fn with_subscription_billing_run_service(mut self, service: Arc<SubscriptionBillingRunService>) -> Self {
        self.subscription_billing_run_service = Some(service);
        self
    }

    /// Set the SubscriptionPlan service.
    pub fn with_subscription_plan_service(mut self, service: Arc<SubscriptionPlanService>) -> Self {
        self.subscription_plan_service = Some(service);
        self
    }

    /// Set the SubscriptionPlanLine service.
    pub fn with_subscription_plan_line_service(mut self, service: Arc<SubscriptionPlanLineService>) -> Self {
        self.subscription_plan_line_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            subscription_service: self.subscription_service.expect("subscription_service is required"),
            subscription_billing_run_service: self.subscription_billing_run_service.expect("subscription_billing_run_service is required"),
            subscription_plan_service: self.subscription_plan_service.expect("subscription_plan_service is required"),
            subscription_plan_line_service: self.subscription_plan_line_service.expect("subscription_plan_line_service is required"),
        }
    }
}
