//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    subscription_handler::create_subscription_routes,
    subscription_billing_run_handler::create_subscription_billing_run_routes,
    subscription_plan_handler::create_subscription_plan_routes,
    subscription_plan_line_handler::create_subscription_plan_line_routes,
};

use crate::application::service::{
    SubscriptionService,
    SubscriptionBillingRunService,
    SubscriptionPlanService,
    SubscriptionPlanLineService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub subscription: Arc<SubscriptionService>,
    pub subscription_billing_run: Arc<SubscriptionBillingRunService>,
    pub subscription_plan: Arc<SubscriptionPlanService>,
    pub subscription_plan_line: Arc<SubscriptionPlanLineService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Subscription routes (12 Backbone endpoints)
        .merge(create_subscription_routes(services.subscription))
        // SubscriptionBillingRun routes (12 Backbone endpoints)
        .merge(create_subscription_billing_run_routes(services.subscription_billing_run))
        // SubscriptionPlan routes (12 Backbone endpoints)
        .merge(create_subscription_plan_routes(services.subscription_plan))
        // SubscriptionPlanLine routes (12 Backbone endpoints)
        .merge(create_subscription_plan_line_routes(services.subscription_plan_line))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn subscription_routes(service: Arc<SubscriptionService>) -> Router {
        create_subscription_routes(service)
    }

    pub fn subscription_billing_run_routes(service: Arc<SubscriptionBillingRunService>) -> Router {
        create_subscription_billing_run_routes(service)
    }

    pub fn subscription_plan_routes(service: Arc<SubscriptionPlanService>) -> Router {
        create_subscription_plan_routes(service)
    }

    pub fn subscription_plan_line_routes(service: Arc<SubscriptionPlanLineService>) -> Router {
        create_subscription_plan_line_routes(service)
    }

}
