//! Public events for Subscription module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// SUBSCRIPTION EVENTS
// ============================================================================

/// Event published when a Subscription is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionCreatedEvent {
    pub id: SubscriptionId,
    pub data: SubscriptionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Subscription is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionUpdatedEvent {
    pub id: SubscriptionId,
    pub data: SubscriptionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Subscription is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionDeletedEvent {
    pub id: SubscriptionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUBSCRIPTIONBILLINGRUN EVENTS
// ============================================================================

/// Event published when a SubscriptionBillingRun is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionBillingRunCreatedEvent {
    pub id: SubscriptionBillingRunId,
    pub data: SubscriptionBillingRunDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SubscriptionBillingRun is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionBillingRunUpdatedEvent {
    pub id: SubscriptionBillingRunId,
    pub data: SubscriptionBillingRunDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SubscriptionBillingRun is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionBillingRunDeletedEvent {
    pub id: SubscriptionBillingRunId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUBSCRIPTIONPLAN EVENTS
// ============================================================================

/// Event published when a SubscriptionPlan is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanCreatedEvent {
    pub id: SubscriptionPlanId,
    pub data: SubscriptionPlanDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SubscriptionPlan is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanUpdatedEvent {
    pub id: SubscriptionPlanId,
    pub data: SubscriptionPlanDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SubscriptionPlan is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanDeletedEvent {
    pub id: SubscriptionPlanId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SUBSCRIPTIONPLANLINE EVENTS
// ============================================================================

/// Event published when a SubscriptionPlanLine is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanLineCreatedEvent {
    pub id: SubscriptionPlanLineId,
    pub data: SubscriptionPlanLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SubscriptionPlanLine is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanLineUpdatedEvent {
    pub id: SubscriptionPlanLineId,
    pub data: SubscriptionPlanLineDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SubscriptionPlanLine is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanLineDeletedEvent {
    pub id: SubscriptionPlanLineId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Subscription module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SubscriptionEvent {
    SubscriptionCreated(SubscriptionCreatedEvent),
    SubscriptionUpdated(SubscriptionUpdatedEvent),
    SubscriptionDeleted(SubscriptionDeletedEvent),
    SubscriptionBillingRunCreated(SubscriptionBillingRunCreatedEvent),
    SubscriptionBillingRunUpdated(SubscriptionBillingRunUpdatedEvent),
    SubscriptionBillingRunDeleted(SubscriptionBillingRunDeletedEvent),
    SubscriptionPlanCreated(SubscriptionPlanCreatedEvent),
    SubscriptionPlanUpdated(SubscriptionPlanUpdatedEvent),
    SubscriptionPlanDeleted(SubscriptionPlanDeletedEvent),
    SubscriptionPlanLineCreated(SubscriptionPlanLineCreatedEvent),
    SubscriptionPlanLineUpdated(SubscriptionPlanLineUpdatedEvent),
    SubscriptionPlanLineDeleted(SubscriptionPlanLineDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for SubscriptionEventMetadata {
    fn default() -> Self {
        Self {
            module: "subscription",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
