//! Subscription Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Subscription exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use subscription::exports::{SubscriptionDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `SubscriptionDto` - Data transfer object for Subscription
/// - `SubscriptionSummary` - Summary view of Subscription
/// - `SubscriptionId` - Type-safe ID wrapper
/// - `SubscriptionBillingRunDto` - Data transfer object for SubscriptionBillingRun
/// - `SubscriptionBillingRunSummary` - Summary view of SubscriptionBillingRun
/// - `SubscriptionBillingRunId` - Type-safe ID wrapper
/// - `SubscriptionPlanDto` - Data transfer object for SubscriptionPlan
/// - `SubscriptionPlanSummary` - Summary view of SubscriptionPlan
/// - `SubscriptionPlanId` - Type-safe ID wrapper
/// - `SubscriptionPlanLineDto` - Data transfer object for SubscriptionPlanLine
/// - `SubscriptionPlanLineSummary` - Summary view of SubscriptionPlanLine
/// - `SubscriptionPlanLineId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `SubscriptionCreatedEvent` - Published when Subscription is created
/// - `SubscriptionUpdatedEvent` - Published when Subscription is updated
/// - `SubscriptionDeletedEvent` - Published when Subscription is deleted
/// - `SubscriptionBillingRunCreatedEvent` - Published when SubscriptionBillingRun is created
/// - `SubscriptionBillingRunUpdatedEvent` - Published when SubscriptionBillingRun is updated
/// - `SubscriptionBillingRunDeletedEvent` - Published when SubscriptionBillingRun is deleted
/// - `SubscriptionPlanCreatedEvent` - Published when SubscriptionPlan is created
/// - `SubscriptionPlanUpdatedEvent` - Published when SubscriptionPlan is updated
/// - `SubscriptionPlanDeletedEvent` - Published when SubscriptionPlan is deleted
/// - `SubscriptionPlanLineCreatedEvent` - Published when SubscriptionPlanLine is created
/// - `SubscriptionPlanLineUpdatedEvent` - Published when SubscriptionPlanLine is updated
/// - `SubscriptionPlanLineDeletedEvent` - Published when SubscriptionPlanLine is deleted
pub struct ExportSummary;
