//! Public services for Subscription module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Subscription module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait SubscriptionQueryService: Send + Sync {
    /// Get Subscription by ID
    async fn get_subscription(&self, id: SubscriptionId) -> Result<Option<SubscriptionDto>>;

    /// Get Subscription summary by ID
    async fn get_subscription_summary(&self, id: SubscriptionId) -> Result<Option<SubscriptionSummary>>;

    /// Check if Subscription exists
    async fn subscription_exists(&self, id: SubscriptionId) -> Result<bool>;

    /// Get SubscriptionBillingRun by ID
    async fn get_subscription_billing_run(&self, id: SubscriptionBillingRunId) -> Result<Option<SubscriptionBillingRunDto>>;

    /// Get SubscriptionBillingRun summary by ID
    async fn get_subscription_billing_run_summary(&self, id: SubscriptionBillingRunId) -> Result<Option<SubscriptionBillingRunSummary>>;

    /// Check if SubscriptionBillingRun exists
    async fn subscription_billing_run_exists(&self, id: SubscriptionBillingRunId) -> Result<bool>;

    /// Get SubscriptionPlan by ID
    async fn get_subscription_plan(&self, id: SubscriptionPlanId) -> Result<Option<SubscriptionPlanDto>>;

    /// Get SubscriptionPlan summary by ID
    async fn get_subscription_plan_summary(&self, id: SubscriptionPlanId) -> Result<Option<SubscriptionPlanSummary>>;

    /// Check if SubscriptionPlan exists
    async fn subscription_plan_exists(&self, id: SubscriptionPlanId) -> Result<bool>;

    /// Get SubscriptionPlanLine by ID
    async fn get_subscription_plan_line(&self, id: SubscriptionPlanLineId) -> Result<Option<SubscriptionPlanLineDto>>;

    /// Get SubscriptionPlanLine summary by ID
    async fn get_subscription_plan_line_summary(&self, id: SubscriptionPlanLineId) -> Result<Option<SubscriptionPlanLineSummary>>;

    /// Check if SubscriptionPlanLine exists
    async fn subscription_plan_line_exists(&self, id: SubscriptionPlanLineId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of SubscriptionQueryService
pub struct SubscriptionQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> SubscriptionQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
