//! Public types for Subscription module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// SUBSCRIPTION TYPES
// ============================================================================

/// Type-safe ID for Subscription
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SubscriptionId(pub Uuid);

impl SubscriptionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SubscriptionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SubscriptionId> for Uuid {
    fn from(id: SubscriptionId) -> Self {
        id.0
    }
}

/// Data transfer object for Subscription
///
/// This is the public representation of Subscription for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionDto {
    pub id: SubscriptionId,
    pub subscription_number: String,
    pub company_id: Uuid,
    pub customer_id: Uuid,
    pub plan_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub status: SubscriptionStatus,
    pub started_at: NaiveDate,
    pub current_period_start: NaiveDate,
    pub current_period_end: NaiveDate,
    pub next_billing_date: NaiveDate,
    pub currency: String,
    pub cancelled_at: Option<NaiveDate>,
    pub ended_at: Option<NaiveDate>,
    pub metadata: serde_json::Value,
}

/// Summary view of Subscription for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionSummary {
    pub id: SubscriptionId,
    pub status: SubscriptionStatus,
}

/// Reference to Subscription for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionRef {
    pub id: SubscriptionId,
}

// ============================================================================
// SUBSCRIPTIONBILLINGRUN TYPES
// ============================================================================

/// Type-safe ID for SubscriptionBillingRun
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SubscriptionBillingRunId(pub Uuid);

impl SubscriptionBillingRunId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SubscriptionBillingRunId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SubscriptionBillingRunId> for Uuid {
    fn from(id: SubscriptionBillingRunId) -> Self {
        id.0
    }
}

/// Data transfer object for SubscriptionBillingRun
///
/// This is the public representation of SubscriptionBillingRun for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionBillingRunDto {
    pub id: SubscriptionBillingRunId,
    pub subscription_id: Uuid,
    pub company_id: Uuid,
    pub period_start: NaiveDate,
    pub period_end: NaiveDate,
    pub due_date: NaiveDate,
    pub grand_total: Decimal,
    pub status: BillingRunStatus,
    pub invoice_id: Option<Uuid>,
    pub idempotency_key: String,
    pub attempted_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of SubscriptionBillingRun for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionBillingRunSummary {
    pub id: SubscriptionBillingRunId,
    pub status: BillingRunStatus,
}

/// Reference to SubscriptionBillingRun for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionBillingRunRef {
    pub id: SubscriptionBillingRunId,
}

// ============================================================================
// SUBSCRIPTIONPLAN TYPES
// ============================================================================

/// Type-safe ID for SubscriptionPlan
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SubscriptionPlanId(pub Uuid);

impl SubscriptionPlanId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SubscriptionPlanId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SubscriptionPlanId> for Uuid {
    fn from(id: SubscriptionPlanId) -> Self {
        id.0
    }
}

/// Data transfer object for SubscriptionPlan
///
/// This is the public representation of SubscriptionPlan for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanDto {
    pub id: SubscriptionPlanId,
    pub plan_code: String,
    pub name: String,
    pub description: Option<String>,
    pub company_id: Uuid,
    pub billing_cycle: BillingCycle,
    pub billing_day: i32,
    pub currency: String,
    pub receivable_account_id: Uuid,
    pub price: Decimal,
    pub trial_days: Option<i32>,
    pub status: SubscriptionPlanStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of SubscriptionPlan for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanSummary {
    pub id: SubscriptionPlanId,
    pub name: String,
    pub status: SubscriptionPlanStatus,
}

/// Reference to SubscriptionPlan for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanRef {
    pub id: SubscriptionPlanId,
}

// ============================================================================
// SUBSCRIPTIONPLANLINE TYPES
// ============================================================================

/// Type-safe ID for SubscriptionPlanLine
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SubscriptionPlanLineId(pub Uuid);

impl SubscriptionPlanLineId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SubscriptionPlanLineId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SubscriptionPlanLineId> for Uuid {
    fn from(id: SubscriptionPlanLineId) -> Self {
        id.0
    }
}

/// Data transfer object for SubscriptionPlanLine
///
/// This is the public representation of SubscriptionPlanLine for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanLineDto {
    pub id: SubscriptionPlanLineId,
    pub plan_id: Uuid,
    pub item_id: Uuid,
    pub account_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of SubscriptionPlanLine for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanLineSummary {
    pub id: SubscriptionPlanLineId,
}

/// Reference to SubscriptionPlanLine for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SubscriptionPlanLineRef {
    pub id: SubscriptionPlanLineId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
