//! Subscription Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::SubscriptionService;
pub use application::service::SubscriptionBillingRunService;
pub use application::service::SubscriptionPlanService;
pub use application::service::SubscriptionPlanLineService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Subscription module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let subscription = SubscriptionModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = subscription.all_crud_routes();
/// ```
pub struct SubscriptionModule {
    pub(crate) subscription_service: Arc<SubscriptionService>,
    pub(crate) subscription_billing_run_service: Arc<SubscriptionBillingRunService>,
    pub(crate) subscription_plan_service: Arc<SubscriptionPlanService>,
    pub(crate) subscription_plan_line_service: Arc<SubscriptionPlanLineService>,
    // <<< CUSTOM FIELDS
    // END CUSTOM
}

impl SubscriptionModule {
    /// Create a new module builder
    pub fn builder() -> SubscriptionModuleBuilder {
        SubscriptionModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_subscription_routes,
            create_subscription_billing_run_routes,
            create_subscription_plan_routes,
            create_subscription_plan_line_routes,
        };

        Router::new()
            .merge(create_subscription_routes(self.subscription_service.clone()))
            .merge(create_subscription_billing_run_routes(self.subscription_billing_run_service.clone()))
            .merge(create_subscription_plan_routes(self.subscription_plan_service.clone()))
            .merge(create_subscription_plan_line_routes(self.subscription_plan_line_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_subscription_read_routes,
            create_subscription_billing_run_read_routes,
            create_subscription_plan_read_routes,
            create_subscription_plan_line_read_routes,
        };

        Router::new()
            .merge(create_subscription_read_routes(self.subscription_service.clone()))
            .merge(create_subscription_billing_run_read_routes(self.subscription_billing_run_service.clone()))
            .merge(create_subscription_plan_read_routes(self.subscription_plan_service.clone()))
            .merge(create_subscription_plan_line_read_routes(self.subscription_plan_line_service.clone()))
    }

    // <<< CUSTOM METHODS
    // END CUSTOM
}

/// Builder for SubscriptionModule
pub struct SubscriptionModuleBuilder {
    db_pool: Option<PgPool>,
}

impl SubscriptionModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<SubscriptionModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Subscription service
        let subscription_repository = Arc::new(SubscriptionRepository::new(db_pool.clone()));
        let subscription_service = Arc::new(SubscriptionService::with_repository(subscription_repository.clone()));

        // SubscriptionBillingRun service
        let subscription_billing_run_repository = Arc::new(SubscriptionBillingRunRepository::new(db_pool.clone()));
        let subscription_billing_run_service = Arc::new(SubscriptionBillingRunService::with_repository(subscription_billing_run_repository.clone()));

        // SubscriptionPlan service
        let subscription_plan_repository = Arc::new(SubscriptionPlanRepository::new(db_pool.clone()));
        let subscription_plan_service = Arc::new(SubscriptionPlanService::with_repository(subscription_plan_repository.clone()));

        // SubscriptionPlanLine service
        let subscription_plan_line_repository = Arc::new(SubscriptionPlanLineRepository::new(db_pool.clone()));
        let subscription_plan_line_service = Arc::new(SubscriptionPlanLineService::with_repository(subscription_plan_line_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(SubscriptionModule {
            subscription_service,
            subscription_billing_run_service,
            subscription_plan_service,
            subscription_plan_line_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for SubscriptionModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
