//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod subscription_usecases;
pub mod subscription_billing_run_usecases;
pub mod subscription_plan_usecases;
pub mod subscription_plan_line_usecases;

pub use subscription_usecases::{
    CreateSubscriptionUseCase, UpdateSubscriptionUseCase, GetSubscriptionUseCase,
    DeleteSubscriptionUseCase, ListSubscriptionUseCase,
};
pub use subscription_billing_run_usecases::{
    CreateSubscriptionBillingRunUseCase, UpdateSubscriptionBillingRunUseCase, GetSubscriptionBillingRunUseCase,
    DeleteSubscriptionBillingRunUseCase, ListSubscriptionBillingRunUseCase,
};
pub use subscription_plan_usecases::{
    CreateSubscriptionPlanUseCase, UpdateSubscriptionPlanUseCase, GetSubscriptionPlanUseCase,
    DeleteSubscriptionPlanUseCase, ListSubscriptionPlanUseCase,
};
pub use subscription_plan_line_usecases::{
    CreateSubscriptionPlanLineUseCase, UpdateSubscriptionPlanLineUseCase, GetSubscriptionPlanLineUseCase,
    DeleteSubscriptionPlanLineUseCase, ListSubscriptionPlanLineUseCase,
};

// <<< CUSTOM
// END CUSTOM
