//! Use case type aliases for Subscription aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSubscriptionDto, UpdateSubscriptionDto};
use crate::application::service::SubscriptionService;
use crate::domain::entity::Subscription;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSubscriptionUseCase = CreateUseCase<Subscription, CreateSubscriptionDto, SubscriptionService>;
pub type UpdateSubscriptionUseCase = UpdateUseCase<Subscription, UpdateSubscriptionDto, SubscriptionService>;
pub type GetSubscriptionUseCase    = GetUseCase<Subscription, SubscriptionService>;
pub type DeleteSubscriptionUseCase = DeleteUseCase<Subscription, SubscriptionService>;
pub type ListSubscriptionUseCase   = ListUseCase<Subscription, SubscriptionService>;

// <<< CUSTOM
// END CUSTOM
