//! Use case type aliases for SubscriptionPlanLine aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSubscriptionPlanLineDto, UpdateSubscriptionPlanLineDto};
use crate::application::service::SubscriptionPlanLineService;
use crate::domain::entity::SubscriptionPlanLine;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSubscriptionPlanLineUseCase = CreateUseCase<SubscriptionPlanLine, CreateSubscriptionPlanLineDto, SubscriptionPlanLineService>;
pub type UpdateSubscriptionPlanLineUseCase = UpdateUseCase<SubscriptionPlanLine, UpdateSubscriptionPlanLineDto, SubscriptionPlanLineService>;
pub type GetSubscriptionPlanLineUseCase    = GetUseCase<SubscriptionPlanLine, SubscriptionPlanLineService>;
pub type DeleteSubscriptionPlanLineUseCase = DeleteUseCase<SubscriptionPlanLine, SubscriptionPlanLineService>;
pub type ListSubscriptionPlanLineUseCase   = ListUseCase<SubscriptionPlanLine, SubscriptionPlanLineService>;

// <<< CUSTOM
// END CUSTOM
