//! Use case type aliases for SubscriptionBillingRun aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSubscriptionBillingRunDto, UpdateSubscriptionBillingRunDto};
use crate::application::service::SubscriptionBillingRunService;
use crate::domain::entity::SubscriptionBillingRun;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSubscriptionBillingRunUseCase = CreateUseCase<SubscriptionBillingRun, CreateSubscriptionBillingRunDto, SubscriptionBillingRunService>;
pub type UpdateSubscriptionBillingRunUseCase = UpdateUseCase<SubscriptionBillingRun, UpdateSubscriptionBillingRunDto, SubscriptionBillingRunService>;
pub type GetSubscriptionBillingRunUseCase    = GetUseCase<SubscriptionBillingRun, SubscriptionBillingRunService>;
pub type DeleteSubscriptionBillingRunUseCase = DeleteUseCase<SubscriptionBillingRun, SubscriptionBillingRunService>;
pub type ListSubscriptionBillingRunUseCase   = ListUseCase<SubscriptionBillingRun, SubscriptionBillingRunService>;

// <<< CUSTOM
// END CUSTOM
