//! Use case type aliases for SubscriptionPlan aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSubscriptionPlanDto, UpdateSubscriptionPlanDto};
use crate::application::service::SubscriptionPlanService;
use crate::domain::entity::SubscriptionPlan;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSubscriptionPlanUseCase = CreateUseCase<SubscriptionPlan, CreateSubscriptionPlanDto, SubscriptionPlanService>;
pub type UpdateSubscriptionPlanUseCase = UpdateUseCase<SubscriptionPlan, UpdateSubscriptionPlanDto, SubscriptionPlanService>;
pub type GetSubscriptionPlanUseCase    = GetUseCase<SubscriptionPlan, SubscriptionPlanService>;
pub type DeleteSubscriptionPlanUseCase = DeleteUseCase<SubscriptionPlan, SubscriptionPlanService>;
pub type ListSubscriptionPlanUseCase   = ListUseCase<SubscriptionPlan, SubscriptionPlanService>;

// <<< CUSTOM
// END CUSTOM
