//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod subscription_handler;
pub mod subscription_billing_run_handler;
pub mod subscription_plan_handler;
pub mod subscription_plan_line_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use subscription_handler::{create_subscription_routes, create_subscription_read_routes, create_subscription_write_routes};
pub use subscription_billing_run_handler::{create_subscription_billing_run_routes, create_subscription_billing_run_read_routes, create_subscription_billing_run_write_routes};
pub use subscription_plan_handler::{create_subscription_plan_routes, create_subscription_plan_read_routes, create_subscription_plan_write_routes};
pub use subscription_plan_line_handler::{create_subscription_plan_line_routes, create_subscription_plan_line_read_routes, create_subscription_plan_line_write_routes};
// <<< CUSTOM
// END CUSTOM
